frame_id: map

map_list:
  - path: /home/uchiito-h/TsukubaChallengeLog/2019/11_04_map_change/maps/map1.yaml
    lat: 36.109211738
    lon: 140.100415260
    alt: 59.7116
    rad: 0.0
  - path: /home/uchiito-h/TsukubaChallengeLog/2019/11_04_map_change/maps/map2.yaml
    lat: 36.109211738
    lon: 140.100415260
    alt: 59.7116
    rad: 0.0
